# Alacritty Configuration
# Doom One Theme with Source Code Pro Font

[window]
# Window dimensions
dimensions = { columns = 120, lines = 40 }

# Window padding
padding = { x = 10, y = 10 }

# Window decorations
decorations = "full"

# Startup mode
startup_mode = "Windowed"

# Window title
title = "Alacritty"

# Dynamic title
dynamic_title = true

# Window opacity
opacity = 0.95

[scrolling]
# Maximum number of lines in the scrollback buffer
history = 10000

# Scrolling multiplier
multiplier = 3

[font]
# Normal font face - Using MesloLGS Nerd Font (recommended for Powerlevel10k)
# Alternative: Use "SauceCodePro Nerd Font" if you prefer Source Code Pro
normal = { family = "MesloLGS Nerd Font", style = "Regular" }

# Bold font face
bold = { family = "MesloLGS Nerd Font", style = "Bold" }

# Italic font face
italic = { family = "MesloLGS Nerd Font", style = "Italic" }

# Bold italic font face
bold_italic = { family = "MesloLGS Nerd Font", style = "Bold Italic" }

# Font size
size = 13.0

# Offset for character spacing
offset = { x = 0, y = 0 }

# Glyph offset
glyph_offset = { x = 0, y = 0 }

# Use built-in font for box drawing characters
builtin_box_drawing = true

[colors]
# Doom One Theme Colors
draw_bold_text_with_bright_colors = true

# Primary colors
[colors.primary]
background = "#282c34"
foreground = "#bbc2cf"

# Cursor colors
[colors.cursor]
text = "#282c34"
cursor = "#51afef"

# Selection colors
[colors.selection]
text = "#bbc2cf"
background = "#3e4451"

# Normal colors
[colors.normal]
black   = "#1c1f24"
red     = "#ff6c6b"
green   = "#98be65"
yellow  = "#ecbe7b"
blue    = "#51afef"
magenta = "#c678dd"
cyan    = "#46d9ff"
white   = "#bbc2cf"

# Bright colors
[colors.bright]
black   = "#5b6268"
red     = "#da8548"
green   = "#4db5bd"
yellow  = "#ecbe7b"
blue    = "#51afef"
magenta = "#c678dd"
cyan    = "#46d9ff"
white   = "#dfdfdf"

# Dim colors (optional)
[colors.dim]
black   = "#1c1f24"
red     = "#ff6c6b"
green   = "#98be65"
yellow  = "#ecbe7b"
blue    = "#51afef"
magenta = "#c678dd"
cyan    = "#46d9ff"
white   = "#bbc2cf"

[bell]
# Visual bell animation
animation = "EaseOutExpo"
duration = 150
color = "#ffffff"

[cursor]
# Cursor style
style = { shape = "Block", blinking = "Off" }

# Vi mode cursor style
vi_mode_style = { shape = "Block", blinking = "Off" }

# Cursor blinking interval
blink_interval = 750

# Cursor blink timeout
blink_timeout = 0

# Unfocused hollow cursor
unfocused_hollow = true

# Thickness of the cursor
thickness = 0.15

[mouse]
# Hide mouse cursor when typing
hide_when_typing = true

# Mouse bindings
[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"

[selection]
# Semantic selection
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

# Save selection to clipboard
save_to_clipboard = true

[keyboard]
# Key bindings
[[keyboard.bindings]]
key = "V"
mods = "Command"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Command"
action = "Copy"

[[keyboard.bindings]]
key = "Q"
mods = "Command"
action = "Quit"

[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "SpawnNewInstance"

[[keyboard.bindings]]
key = "F"
mods = "Command|Control"
action = "ToggleFullscreen"

[[keyboard.bindings]]
key = "Plus"
mods = "Command"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Command"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "Key0"
mods = "Command"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "K"
mods = "Command"
action = "ClearHistory"

[[keyboard.bindings]]
key = "L"
mods = "Control"
action = "ClearLogNotice"

[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
action = "ScrollPageDown"

[[keyboard.bindings]]
key = "Home"
mods = "Shift"
action = "ScrollToTop"

[[keyboard.bindings]]
key = "End"
mods = "Shift"
action = "ScrollToBottom"

# Alt as Meta key for macOS
[[keyboard.bindings]]
key = "A"
mods = "Alt"
chars = "\u001ba"

[[keyboard.bindings]]
key = "B"
mods = "Alt"
chars = "\u001bb"

[[keyboard.bindings]]
key = "C"
mods = "Alt"
chars = "\u001bc"

[[keyboard.bindings]]
key = "D"
mods = "Alt"
chars = "\u001bd"

[[keyboard.bindings]]
key = "E"
mods = "Alt"
chars = "\u001be"

[[keyboard.bindings]]
key = "F"
mods = "Alt"
chars = "\u001bf"

[[keyboard.bindings]]
key = "G"
mods = "Alt"
chars = "\u001bg"

[[keyboard.bindings]]
key = "H"
mods = "Alt"
chars = "\u001bh"

[[keyboard.bindings]]
key = "I"
mods = "Alt"
chars = "\u001bi"

[[keyboard.bindings]]
key = "J"
mods = "Alt"
chars = "\u001bj"

[[keyboard.bindings]]
key = "K"
mods = "Alt"
chars = "\u001bk"

[[keyboard.bindings]]
key = "L"
mods = "Alt"
chars = "\u001bl"

[[keyboard.bindings]]
key = "M"
mods = "Alt"
chars = "\u001bm"

[[keyboard.bindings]]
key = "N"
mods = "Alt"
chars = "\u001bn"

[[keyboard.bindings]]
key = "O"
mods = "Alt"
chars = "\u001bo"

[[keyboard.bindings]]
key = "P"
mods = "Alt"
chars = "\u001bp"

[[keyboard.bindings]]
key = "Q"
mods = "Alt"
chars = "\u001bq"

[[keyboard.bindings]]
key = "R"
mods = "Alt"
chars = "\u001br"

[[keyboard.bindings]]
key = "S"
mods = "Alt"
chars = "\u001bs"

[[keyboard.bindings]]
key = "T"
mods = "Alt"
chars = "\u001bt"

[[keyboard.bindings]]
key = "U"
mods = "Alt"
chars = "\u001bu"

[[keyboard.bindings]]
key = "V"
mods = "Alt"
chars = "\u001bv"

[[keyboard.bindings]]
key = "W"
mods = "Alt"
chars = "\u001bw"

[[keyboard.bindings]]
key = "X"
mods = "Alt"
chars = "\u001bx"

[[keyboard.bindings]]
key = "Y"
mods = "Alt"
chars = "\u001by"

[[keyboard.bindings]]
key = "Z"
mods = "Alt"
chars = "\u001bz"

# Terminal configuration
[terminal]
# Shell configuration
shell = { program = "/opt/homebrew/bin/zsh", args = ["--login"] }

# Environment variables
[env]
TERM = "xterm-256color"

# General configuration
[general]
# Live config reload
live_config_reload = true

# Offer IPC using alacritty msg (removed - ipc_socket is no longer supported)
